export {
  adoptReportedRanges,
  applyCaption,
  applyOutcome,
  applyRefuseReason,
  applyRows,
  macsMatch,
  normalizeMac,
  readdressContinuity,
  shortMac,
  spansMatch,
  type AppliedRange,
  type ApplyResult,
  type ApplyRow,
  type ApplyStatus,
  type ReaddressDecision,
  type ReaddressStep,
} from "./apply.ts";
export {
  allOffConfirmCopy,
  allOffDockCaption,
  allOffRetryLabel,
  allOffRowLabel,
  allOffSummary,
  buildDeleteChecks,
  canDelete,
  deleteProgress,
  deleteRefuseReason,
  manageCaption,
  type AllOffCancelled,
  type AllOffLiveHint,
  type AllOffResult,
  type AllOffRow,
  type AllOffRowStatus,
  type DeleteCheck,
  type DeleteCheckKey,
  type DeleteCheckStatus,
} from "./manage.ts";
export { isLitBead, isUnknownBead, type BeadColor } from "./bead.ts";
export { catalogSnapshot, CURRENT_SLICE, type CatalogSnapshot } from "./catalog.ts";
export {
  BLINK_COLOR,
  BLINK_PULSE_MS,
  PREVIEW_SWATCHES,
  beadsFromLive,
  blinkRefuseReason,
  colorsMatch,
  countRangeMatches,
  fixtureCaption,
  hexToRgb,
  parseHexColor,
  parseLiveLeds,
  previewRefuseReason,
  proofLadder,
  resolveLiveTarget,
  rgbToHex,
  shouldRestoreOnEnd,
  type LiveEndKind,
  type LiveMatch,
  type LiveRead,
  type LiveRestoreSnapshot,
  type LiveSession,
  type LiveSessionKind,
  type LiveSource,
  type LiveTarget,
  type ProofRung,
  type SeenByYou,
} from "./live.ts";
export { getController, listControllers } from "./controller/catalog.ts";
export { wledController } from "./controller/wled.ts";
export type {
  ControllerCapability,
  ControllerDescriptor,
} from "./controller/types.ts";
export { listDiscoveryMechanisms } from "./discovery/catalog.ts";
export type {
  DiscoverReasonCode,
  DiscoverRow,
  DiscoverStatus,
  DiscoverVia,
  DiscoveryMechanism,
  DiscoveryMechanismId,
} from "./discovery/types.ts";
export {
  buildRangeDisplay,
  reportedRangeRails,
  type DeclaredRail,
  type DisplayRegion,
  type DriftNote,
  type RangeDisplay,
  type ReportedRail,
} from "./drift.ts";
export {
  emptyLightsPayload,
  normalizeLightLedProductId,
  type Element,
  type Light,
  type LightDetail,
  type LightNameSource,
  type LightReachability,
  type LightView,
  type LightsPayload,
} from "./lights.ts";
export {
  applyResolvedName,
  resolveLightName,
  type LightNameResolution,
} from "./name.ts";
export {
  decideProbeAddress,
  displayHost,
  isLanAllowed,
  normalizeHostKey,
  parseHostPort,
  type AddressDecision,
  type HostPort,
} from "./net/address.ts";
export {
  elementLength,
  firstFreeRange,
  intervalDifference,
  isWholeIndex,
  rangeLabel,
  rangeLengthStory,
  rangesOverlap,
  reconcileDeclaredRangesForLedCount,
  symmetricDifference,
  unionIntervals,
  validateDeclaredRanges,
  type DraftRange,
  type RangeErrorCode,
  type RangeIssue,
  type RangeLengthClip,
  type RangeLengthDrop,
  type RangeLengthKind,
  type RangeLengthReconcile,
  type RangeLengthStory,
  type RangeSpan,
} from "./range.ts";
export {
  defaultStripPreset,
  getStrip,
  getStripPreset,
  listStripPresets,
  listStrips,
  matchingStripPresetId,
  provisionApplyBodyFromPreset,
  provisionDraftFromPreset,
  STRIP_PRESETS,
} from "./strip/catalog.ts";
export {
  inheritLedProductFields,
  isLedFormFactor,
  LED_FORM_FACTORS,
  parseLedProductAttach,
  parseLedProductInput,
  provisionApplyBodyFromProduct,
  provisionDraftFromProduct,
  provisionLedTypeForDriver,
  resolveLedProductAttach,
  seedLedProductsFromPresets,
  validateLedProduct,
} from "./strip/products.ts";
export type {
  InheritedLedFields,
  LedFormFactor,
  LedProduct,
  LedProductAttachParse,
  LedProductAttachResolve,
  LedProductDraft,
  LedProductIssue,
  LedProductParse,
  ProvisionDraftFromProduct,
} from "./strip/products.ts";
export type { StripBead, StripChannel, StripDriverDescriptor } from "./strip/types.ts";
export type { StripPreset } from "./strip/presets.ts";
export { sk6812RgbwStrip } from "./strip/sk6812-rgbw.ts";
export { ws281xStrip } from "./strip/ws281x.ts";
export {
  knownStripKind,
  needsInspectStripKindSeed,
  stripBeadCaption,
  stripHonestyForLight,
} from "./strip/honesty.ts";
export type { StripHonesty, StripHonestySource } from "./strip/honesty.ts";
export {
  PROVISION_GPIO_MAX,
  PROVISION_GPIO_MIN,
  PROVISION_LED_TYPES,
  PROVISION_LENGTH_MAX,
  PROVISION_LENGTH_MIN,
  WLED_COMPATIBILITY_MAPPINGS,
  WLED_SK6812_RGBW_NATIVE_TYPE,
  WLED_WS281X_NATIVE_TYPE,
  baseFirmwareVersion,
  buildProvisionWrite,
  busHasInsList,
  busLength,
  busNativeType,
  busPins,
  draftLedTypeFromSettings,
  isProvisionLedType,
  isSupportedProvisionFirmware,
  ledTypeFromNative,
  parseWledProvision,
  provisionCaption,
  provisionFieldsMatch,
  provisionLedTypeLabel,
  provisionMismatchNote,
  provisionRefuseReason,
  provisionSnapshotMatch,
  rawWledBuses,
  resolveAnyProvisionMapping,
  resolveProvisionMapping,
  resolveWs281xMapping,
  validateProvisionDraft,
  type NativeCompatibilityMapping,
  type ProvisionFieldKey,
  type ProvisionFingerprint,
  type ProvisionLedType,
  type ProvisionRead,
  type ProvisionWriteResult,
  type WledStripProvision,
  type WledStripProvisionDraft,
} from "./provision.ts";
export {
  buildSafeWrite,
  fieldLabel,
  parseWledCfg,
  requestedFields,
  SAFE_FIELDS,
  safeCaption,
  safeFieldsMatch,
  safeInfoNameLagNote,
  safeRefuseReason,
  transitionMs,
  transitionUnitsFromMs,
  validateSafeDraft,
  type SafeFieldKey,
  type SafeFingerprint,
  type SafeRead,
  type SafeWriteResult,
  type WledSafeSettings,
} from "./safe.ts";
export { parseWledPayload, type WledSnapshot } from "./wled/snapshot.ts";
